### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by yuri117** [AcroniTeam/AcroniKeyboards#1]
- [ ] Importar fontes do projeto
- [ ] Fullscreen func
- [ ] Contador de dinheiros
- [ ] Contadores
- [ ] Undo
- [ ] Menu sensível
- [ ] Barra de tarefas aprimorada
- [ ] Separar atualizar do login
- [ ] Continuar sem login

**Comment by yuri117** [comment]
- Smoother
